### ISSUE TITLE
Something's wrong with the UI.

### ISSUE THREAD

**Issue by nxvvvv** [dothq/browser-desktop#101]
![image](https://user-images.githubusercontent.com/34748927/128400692-448e5cfd-f76f-4761-aa2c-4f9e4a258e5c.png)
![image](https://user-images.githubusercontent.com/34748927/128400759-15fc2646-9e00-498d-91aa-cde27ab82057.png)

**Comment by kierandrewett** [comment]
Duplicate

**Comment by v1rtl** [comment]
@EnderDev what's the original issue if all others are duplicate?
