### ISSUE TITLE
Wrong name for the start menu shortcut (Windows 10)

### ISSUE THREAD

**Issue by SKBotNL** [dothq/browser-desktop#102]
**Preflight Checklist**
* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
Installer

**Describe the bug**
The installer makes a start menu shortcut named ".lnk" instead of for example "Dot Browser"

**To Reproduce**
1. Install Dot Browser
2. Open start menu and see a shortcut named ".lnk"

**Expected behavior**
For example "Dot Browser" instead of ".lnk"

**Screenshots**
![iridium_RJTjBSYApX](https://user-images.githubusercontent.com/68018116/110810062-b8f11280-8285-11eb-9078-17fb06b63a8a.png)
![explorer_sPoeL94Yo0](https://user-images.githubusercontent.com/68018116/110810219-dde58580-8285-11eb-8fe1-6aa956615eea.png)

**System Information (please complete the following information):**
 - OS: Windows 10
 - Version: 20H2

**Dot Browser Information (please complete the following information):**
 - Version: Nightly v86.0
 - Site you were on before the bug appeared: None

**Comment by kierandrewett** [comment]
This has been fixed. The shortcut name is now "Dot Browser".
