### ISSUE TITLE
Error when installing from aur

### ISSUE THREAD

**Issue by jakiisheep** [dothq/browser-desktop#104]
I tried installing dot browser from the aur, but it gives me this error message:

error: failed to commit transaction (conflicting files)
dot-bin: /usr/bin/dot exists in filesystem (owned by graphviz)
Errors occurred, no packages were upgraded.

It seems that some package is conflicting with dot? How can I solve this?

**Comment by kierandrewett** [comment]
Can this follow the issue template please?

**Comment by jakiisheep** [comment]
oh sorry

**Comment by jakiisheep** [comment]
how can i use the issue template now

**Comment by SuperZoops** [comment]
There are two -bin packages, use the other one.

**Comment by jakiisheep** [comment]
> There are two -bin packages, use the other one.

What other one? I dont see any other -bin packages, only the git (source) one?

**Comment by kierandrewett** [comment]
https://aur.archlinux.org/packages/dot-bin/
https://aur.archlinux.org/packages/dot-git/

**Comment by SuperZoops** [comment]
> 
> 
> > There are two -bin packages, use the other one.
> 
> What other one? I dont see any other -bin packages, only the git (source) one?

My bad, disregard what I said.

**Comment by jakiisheep** [comment]
Why should building from source fix this? I mean it says it conflicts with another package, wont the same thing happen if I build from source..

**Comment by kierandrewett** [comment]
Building from source is different to building from the AUR, it doesn't check if there are conflicts.

**Comment by nilscript** [comment]
That's not a good solution is it @EnderDev ? Im having the same problem as @sheeepdev. Some name change or at least directory change is in order or else this browser is conflicting with Graphviz which is a direct dependency of gimp.

**Comment by SeerLite** [comment]
The `dot` binary conflicts with `dot` from the graphviz package. graphviz is required by Gimp, which means Dot browser and Gimp can't be installed at the same time. Please consider renaming the binary to something less generic like `dot-browser`.

Thanks

**Comment by jakiisheep** [comment]
@EnderDev Any news on this? Will you rename the binary?

**Comment by kierandrewett** [comment]
Hi, sorry, we've been caught up with other things currently but this is definitely on our roadmap.

**Comment by trickypr** [comment]
This is preventing me from doing stuff on my computer, so I am going to fix it.

**Comment by jakiisheep** [comment]
Seems like the issue is fixed (the PR is merged). Im closing for now.
