### ISSUE TITLE
macOS Build not notarized, causing security block / Bad instructions on release page.

### ISSUE THREAD

**Issue by Enstrayed** [dothq/browser-desktop#105]
**Preflight Checklist**

* [X] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

This issue concerns two things:
* macOS Notarization & avoiding the system blocking the app
* Bad instructions on the releases page

Getting the simple issue out of the way, the installation instructions for macOS on the releases page simply say to "run the .dmg file". This is not how this works, and while most Mac users can figure this out, many do not know how to whitelist an app that is not notarized. 
To fix this, I have created a Notion article that shows how to install and bypass the security block, and I feel that it or simplified steps should be included on the releases page.
Notion article: https://www.notion.so/Dot-Browser-Installation-for-macOS-981fae4e699249cc953f92ffca4ef615
(This is also where I will include instructions on changing the Dot browser icon to a squircle for Big Sur users.)

The core of this issue is that the APP file is not notarized. The only way this could happen as far as I know is to acquire an Apple Developer Account, which is a significant operational cost. Until that happens, special care will need to be taken to ensure users know how to install the app.

**Comment by kierandrewett** [comment]
Notarising Dot Browser is something I want to do, as you said, it's complicated to whitelist the application for the average macOS user. But we should definitely include whitelisting instructions in the install guide. Do you think you could convert this to a PR and add some instructions for whitelisting in https://github.com/dothq/browser-desktop/blob/nightly/.github/RELEASE_TEMPLATE.md?

**Comment by Enstrayed** [comment]
Will do.

**Comment by Enstrayed** [comment]
Pull request including revised installation instructions: https://github.com/dothq/browser-desktop/pull/41

**Comment by kierandrewett** [comment]
Merged.
