### ISSUE TITLE
Update browser_style to match browser theming

### ISSUE THREAD

**Issue by trickypr** [dothq/browser-desktop#107]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
Web Extensions 

**Describe the bug**
Firefox provides a set of style sheets that are optional for web extensions through the [browser_style](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_styles). These style sheets do not match with dot ui and should be updated. This is most important in the sidebar where we want all items to look like they follow one style pattern.

**To Reproduce**
1. Create a basic web extension (I am using [dothq-extensions/notes](https://github.com/dothq-extensions/notes))
2. Set the `browser_style` keyword for one of the keys to true
3. Add the `browser-style` class to all of your buttons, inputs, selects, etc.
4. Observe their lack of matching with the dot ui

**Expected behavior**
The stylesheet provided should fit in with the ui of Dot Browser

**Screenshots**
![image](https://user-images.githubusercontent.com/23250792/123918869-d6043b00-d973-11eb-9c18-53a0e8c40489.png)
_A sidebar styled with `browser-style`_

**System Information (please complete the following information):**
 - OS: Linux

**Dot Browser Information (please complete the following information):**
 - Version: 87.0-2021-05-28
 - Site you were on before the bug appeared: N/A

**Additional context**
I strongly suspect that a script similar (if not the same as) [sidebar-theme.js](https://github.com/dothq/browser-desktop/blob/nightly/common/browser/components/sidebars/generic/sidebar-theme.js) will have to be injected to allow the popup follow the theme the user has installed. I am willing to work on this issue once dothq/browser-desktop#40 has merged.

**Comment by kierandrewett** [comment]
Yes, sidebar-theme.js is what you should use to get the theme colours. All you need to do is just add a script tag in the head loading `chrome://browser/content/sidebars/generic/sidebar-theme.js`. Closing.

**Comment by trickypr** [comment]
CSP blocks including it.

**Comment by kierandrewett** [comment]
Why is the notes sidebar even an extension? Surely it can just be a sidebar item.

**Comment by trickypr** [comment]
I am doing it this way mostly as a proof of consent so I can make sure other devs can add an item to the sidebar as an extension.

**Comment by kierandrewett** [comment]
It's a WebExtension API. Firefox will add the item to the sidebar if the extension requests it. Just install Bitwarden for example and it'll appear in the sidebar. But for internal things like this we should be adding it into the browser, not as another extension.
