### ISSUE TITLE
Old version of firefox means Dot 87 contains many (luckily non-disclosed) security vulnerabilities.

### ISSUE THREAD

**Issue by DumbGameMaker** [dothq/browser-desktop#108]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**

**Describe the bug**
Old version of firefox means Dot 87 contains many (luckily non-disclosed) security vulnerabilities. You can find a page of these vulnerabilities [here](https://www.mozilla.org/en-US/security/advisories/mfsa2021-16/)

*below deleted as they are non-applicable.*

**Comment by kierandrewett** [comment]
We are working on getting version 88.0 shipped as soon as possible.

**Comment by DumbGameMaker** [comment]
that is good :)

**Comment by kierandrewett** [comment]
Closing as 89.0 is being worked on being merged in.
