### ISSUE TITLE
Dot browser experiences performance degridation in comparison to ff

### ISSUE THREAD

**Issue by trickypr** [dothq/browser-desktop#110]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
Gecko

**Describe the bug**
When running performance benchmarks, Dot Browser comes behind firefox in performance.

**To Reproduce**
1. Go to https://browserbench.org/MotionMark1.1/ on both browsers
2. Run the test
3. Observe that dot gets a lower score than firefox

**Expected behavior**
Dot should have the same (or preferably better) performance in benchmarks

**Screenshots**
<img width="576" alt="Screen Shot 2021-06-03 at 8 36 10 am" src="https://user-images.githubusercontent.com/23250792/120561080-727a0280-c3f3-11eb-8d7b-5b6964901f30.png">
_Firefox higher is better_

<img width="608" alt="Screen Shot 2021-06-03 at 8 36 04 am" src="https://user-images.githubusercontent.com/23250792/120561097-79a11080-c3f3-11eb-8012-1ee6e6907cdf.png">
_Dot browser, higher is better_

**System Information (please complete the following information):**
 - OS: macOS
 - Version: Big sur

**Dot Browser Information (please complete the following information):**
 - Version: Nightly v87.0-2021-05-28
 - Site you were on before the bug appeared: N/a

**Additional context**
This may be an issue with compiler configs rather than any explicit changes to browser code.

**Comment by kierandrewett** [comment]
What versions where these benchmarks performed on?

**Comment by trickypr** [comment]
Nightly v87.0-2021-05-28 on MacOS vs ff v88

**Comment by kierandrewett** [comment]
That can't be a fair test then, closing.
