### ISSUE TITLE
Setting the browser language to other language will make it not being able to launch.

### ISSUE THREAD

**Issue by 116s** [dothq/browser-desktop#115]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
chrome://browser/content/browser.xhtml

**Describe the bug**
 Changing the language of the browser and restarting it to apply makes it not possible to launch due to a error.

**To Reproduce**
1. Go to 'Preferences'
2. Scroll down to 'Language'
3. Click on 'Set Alternatives'
4. Click on 'Select a language to add'
5. Add a language, for example, English from United Kingdom.
6. See error (<toolbarbutton id="appMenu-new-tab-button") the arrow points to <

**Expected behavior**
 It shoud apply the language and make dotBrowser able to launch.

**System Information (please complete the following information):**
 - OS: Linux, being more specific to the distribution Fedora.
 - Version: 34

**Dot Browser Information (please complete the following information):**
 - Version:  2021 04 17 08:10:41 
 - Site you were on before the bug appeared: Does not need to be in a website.

**Comment by trickypr** [comment]
There do not appear to be other language options. Would this be fixed @EnderDev?

**Comment by kierandrewett** [comment]
> There do not appear to be other language options. Would this be fixed @EnderDev?

What do you mean by this?
