### ISSUE TITLE
No option to change the default UI theme

### ISSUE THREAD

**Issue by thecodrr** [dothq/browser-desktop#146]
So I also installed Wexond to see what feature-set it has and what you guys have improved. I noticed that they have a Dark/Light mode setting. I found no such setting in the Dot Browser. Maybe this is intended behavior or it will be implemented back in the future? Anyhow, it would be nice to have this option.

### Version Info:
2.0.0-beta.13

**Comment by kierandrewett** [comment]
Merged to dothq/browser-desktop#154
