### ISSUE TITLE
[Request] Match Dot theme to macOS theme

### ISSUE THREAD

**Issue by conorthedev** [dothq/browser-desktop#151]
It'd be nice if you could switch between light and dark depending on what macOS has set.

You can do this with a NPM package called [node-dark-mode](https://github.com/sindresorhus/node-dark-mode).

```javascript
const darkMode = require('dark-mode');

if (darkMode.isDark()) {
    // code
} else {
    // code
}
```

Thanks!

**Comment by kierandrewett** [comment]
Merged to dothq/browser-desktop#154
