### ISSUE TITLE
Login Account

### ISSUE THREAD

**Issue by minhgiau998** [dothq/browser-desktop#217]
When I click to Sign Account in Dot Browser, I have issue when the browser auto open developer console tab and in panel of login, css will be broken. Please fix it, thanks.
![image](https://user-images.githubusercontent.com/39249786/80003643-83b3c880-84eb-11ea-945b-7cc10033a1c5.png)

This is css broken
![image](https://user-images.githubusercontent.com/39249786/80003791-b8c01b00-84eb-11ea-9794-013a1ca46513.png)

**Comment by kierandrewett** [comment]
You did not follow the issue template. Issue closed.

Duplicate of dothq/browser-desktop#201
