### ISSUE TITLE
Emoji Key

### ISSUE THREAD

**Issue by EnderDev** [dothq/browser-desktop#220]

**Comment by kierandrewett** [comment]
@all-contributors please add @bigspeedfpv for code

**Comment by kierandrewett** [comment]
@all-contributors please add @trickypr for code

**Comment by kierandrewett** [comment]
@all-contributors please add @trickypr for code

**Comment by kierandrewett** [comment]
@all-contributors please add @trickypr for code

**Comment by kierandrewett** [comment]
@all-contributors please add @HVEVB for security

**Comment by VeeBack** [comment]
Very cool
