### ISSUE TITLE
No version for Windows10

### ISSUE THREAD

**Issue by kevinmmansour** [dothq/browser-desktop#243]
Please .. Version for Windows 10

**Comment by travexyz** [comment]
acutally there is a release for win10 but it's depecrated (2.1.0)
https://github.com/dothq/browser/releases/download/v2.1.0/Dot.Setup.2.1.0.exe

**Comment by kierandrewett** [comment]
> acutally there is a release for win10 but it's depecrated (2.1.0)
> https://github.com/dothq/browser/releases/download/v2.1.0/Dot.Setup.2.1.0.exe

You can use this version, but I wouldn't recommend it.

**Comment by ioc2e3** [comment]
Unfortunately ...

Still no update so far ...

.
