### ISSUE TITLE
Tab animations are too fast/messed up

### ISSUE THREAD

**Issue by proudmuslim-dev** [dothq/browser-desktop#246]
**Describe the bug**
When opening/closing a tab, the animation appears fast, choppy, and cut off.

**To Reproduce**
1. Launch the browser
2. Open and close a new tab to see what I mean. On firefox, the animation is smooth no matter how fast I spam ctrl + t/w, however on dot it's cut off and choppy.

**Expected behavior**
The animation should be as smooth as the stock firefox one

**System Information (please complete the following information):**
 - OS: Arch ~~btw~~
 - DE: KDE Plasma (latest)

**Dot Browser Information (please complete the following information):**
 - Version: 0.2020.11.14

**Comment by kierandrewett** [comment]
Closing as this is probably outdated now
