### ISSUE TITLE
White space in browser user directory.

### ISSUE THREAD

**Issue by EnderDev** [dothq/browser-desktop#248]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
Browser

**Describe the bug**
When a user directory is created for the first time for the browser in $HOME and $HOME/.cache, it has a space in the directory name because MOZ_APP_VENDOR is "Dot HQ".

**To Reproduce**
1. Build Dot
2. Wipe user folder
3. Check $HOME and $HOME/.cache
4. Folder with name ".dot hq" is created

**Expected behavior**
The directory should be called ".dothq" or ".dot"

**Screenshots**
![image](https://user-images.githubusercontent.com/42723993/103291784-6de49480-49e4-11eb-8b9e-c4809995f254.png)
![image](https://user-images.githubusercontent.com/42723993/103291798-75a43900-49e4-11eb-9c07-06b57887125b.png)

**System Information (please complete the following information):**
 - OS: Arch Linux
 - Version: 5.9.14

**Dot Browser Information (please complete the following information):**
 - Version: master (86.0a1)
 - Site you were on before the bug appeared: N/A
 - 
**Additional context**
N/A

**Comment by kierandrewett** [comment]
Fixed.
