### ISSUE TITLE
Linux build: tsc fails to run as part of the build script

### ISSUE THREAD

**Issue by trickypr** [dothq/browser-desktop#250]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
Firefox browser fork, specifically the custom build system (`melon`).

**Describe the bug**
When first running `./melon download` on linux, I got the following error:
```
./melon: line 4: tsc: command not found
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module '/home/main/Documents/dothq/browser/.dotbuild'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
Presumably, this is because `tsc` should be replaced with `yarn tsc` or `npx tsc`

**To Reproduce**
1. Clone the `browser-ff` repo
2. Open it in terminal
3. Run `./melon download`

**Expected behavior**
The expected behavior is for tsc to run successfully even when it is isn't installed as a global node module.

**Screenshots**

**System Information (please complete the following information):**
 - OS: Manjaro linux
 - Version: idk how versions work on manjaro linux

**Dot Browser Information (please complete the following information):**
 - Version: main at time of posting
 - Site you were on before the bug appeared: N/A

**Additional context**
This error was fixed by me manually running `yarn tsc` in the directory

**Comment by kierandrewett** [comment]
This just requires us to bundle tsc with the project. Anyone want to take on this issue?

**Comment by trickypr** [comment]
No, tsc is already installed as part of the build script. It’s just not added to the path so you have to run it through `yarn tsc`.

**Comment by kierandrewett** [comment]
Hmm alright

**Comment by trickypr** [comment]
I can submit a pull request tomorrow if you want.

**Comment by kierandrewett** [comment]
Sure!

**Comment by andybrwr** [comment]
Addressed in https://github.com/dothq/browser-ff/commit/6c9d2fec3f19c7c2dd612063ebe3bf26f5d6bcef
