### ISSUE TITLE
[Bug] Tab's width is always the same size

### ISSUE THREAD

**Issue by marc2332** [dothq/browser-desktop#251]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
No idea.

**Describe the bug**
Website's tabs always have the same size, even when collapsing.

**To Reproduce**
Open a lot of tabs, enough for Dot to try to collapse them.

**Expected behavior**
It should reduce it's width:
![image](https://user-images.githubusercontent.com/38158676/106328143-97ad0780-627f-11eb-84c1-20a44fce0c4e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/38158676/106328106-8663fb00-627f-11eb-8777-0978d4844590.png)

**System Information (please complete the following information):**
 - OS: Windows
 - Version: 10

**Dot Browser Information (please complete the following information):**
 - Version: 84.0.2

**Comment by kierandrewett** [comment]
Fixed.
