### ISSUE TITLE
[BUG] Windows Installer creates shortcut named ".Ink"

### ISSUE THREAD

**Issue by ejaz4** [dothq/browser-desktop#256]
**Preflight Checklist**
* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
Installer

**Describe the bug**
The Windows Installer creates shortcuts with nothing but the extension. (".Ink")

**To Reproduce**
1. Install [Dot Nightly v86.0](https://github.com/dothq/browser-ff/releases/tag/86.0-d1d2c90)
2. Go through the installation
3. Check your desktop and start menu entries

**Expected behavior**
The shortcuts be created with their proper name (e.g "Dot Browser", "Dot", .etc)

**Screenshots**
![image](https://user-images.githubusercontent.com/73548455/110810186-7297b580-827d-11eb-8ca5-e0427bf73a02.png)
![image](https://user-images.githubusercontent.com/73548455/110810216-79bec380-827d-11eb-80e3-57d9134104eb.png)
![image](https://user-images.githubusercontent.com/73548455/110810242-817e6800-827d-11eb-8b52-ae6575c6809b.png)

**System Information (please complete the following information):**
 - OS: Windows NT 10.0
 - Version: 20H2

**Dot Browser Information (please complete the following information):**
 - Version: 86.0
 - Site you were on before the bug appeared: N/A

**Comment by kierandrewett** [comment]
See dothq/browser-desktop#102, closing.
