### ISSUE TITLE
"Updating" in the about Dot Browser menu reverts it back to Firefox

### ISSUE THREAD

**Issue by SKBotNL** [dothq/browser-desktop#257]
**Preflight Checklist**
* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
About Dot Browser window - Browser

**Describe the bug**
"Updating" Dot Browser in the about dot browser menu resets/reverts dot browser to firefox

**To Reproduce**
1. Three dots > Help > About Dot Browser
2. Click on "Restart to update Dot Browser" (it might download the "update" first)
3. Dot Browser closes, dot.exe is changed with firefox.exe
4. Open firefox.exe
5. Reset/revert back to Firefox

**Expected behavior**
That there is no "Restart to update Dot Browser" or that it is an actual update for Dot Browser.

**Screenshots**
![dot_W1bNvUBop7](https://user-images.githubusercontent.com/68018116/110850247-d89d3080-82af-11eb-9406-06e533e46fe2.png)

**System Information (please complete the following information):**
 - OS: Windows 10
 - Version: 20H2

**Dot Browser Information (please complete the following information):**
 - Version: Nightly 86
 - Site you were on before the bug appeared: N/A

**Comment by kierandrewett** [comment]
@trevorthalacker We really need to swap out the Mozilla update server with ours soon

**Comment by ItsJamie9494** [comment]
It's very close to being done. Will probably either finish this weekend or next week. Most likely this weekend.

**Comment by kierandrewett** [comment]
Fixed in dothq/browser-desktop@698d96bd5ba4dca7d3017ff963b5c2c57e7cf249
