### ISSUE TITLE
The group not saving when I close the window

### ISSUE THREAD

**Issue by LWJerri** [dothq/browser-desktop#258]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
Browser main menu.

**Describe the bug**
I'm creating a new group and when I close the window my groups delete.

**To Reproduce**
1. Create new group.
2. Close window and reopen.
3. See result.

**Screenshots**
-

**System Information (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 20H2

**Dot Browser Information (please complete the following information):**
 - Version: 2.1.0.
 - Website: Dot main page.

**Comment by kierandrewett** [comment]
2.1.0 has been deprecated for 8 months now, closing.
