### ISSUE TITLE
Whole UI is broken on Windows

### ISSUE THREAD

**Issue by SKBotNL** [dothq/browser-desktop#260]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
Browser

**Describe the bug**
The whole UI is broken

**To Reproduce**
1. Install Dot Browser
2. Open Dot browser
3. See error

**Expected behavior**
That the UI just looks good/works good

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/68018116/113471087-550fd300-945a-11eb-9b90-c0dcc22719f6.png)

**System Information (please complete the following information):**
 - OS: Windows 10
 - Version: 20H2

**Dot Browser Information (please complete the following information):**
 - Version: 87.0 Nightly
 - Site you were on before the bug appeared: N/A

Idk if this is intended somehow (testing UI idk) but its totally broken.

**Comment by ItsJamie9494** [comment]
The UI is currently undergoing some modifications, so this is expected.


2 Apr 2021, 23:55 by ***@***.***:

**Comment by SKBotNL** [comment]
> The UI is currently undergoing some modifications, so this is expected.

Yeah I already thought something like that was going on.

**Comment by kierandrewett** [comment]
Fixed in dothq/browser-desktop@dfec81d5e46704f736755f7bd333a57d5748c6a5
