### ISSUE TITLE
detectportal mozilla requests should be disabled by default, if possible.

### ISSUE THREAD

**Issue by bm92aWJldnJvcw** [dothq/browser-desktop#261]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Describe the bug**
Browser sends detectportal mozilla requests.

**To Reproduce**
1. Open requests capturing utility like Fiddler.
2. make sure to enable decrypt https requests.
3. open fiddler and then open Dot Browser to see init requests sent.
4. see detectportal mozilla requests are sent.

**Expected behavior**
should not send these requests by default if possible. We can disable it in about:config by toggling network.captive-portal-service.enabled to false but not before we open the browser.

**System Information (please complete the following information):**
 - OS: Windows 10 2019 server

**Dot Browser Information (please complete the following information):**
 - Version: latest (87)

**Comment by ItsJamie9494** [comment]
`network.captive-portal-service.enabled` looks like it's automatically disabled in Dot. However, it looks like there might be another setting that also uses `detectportal.firefox.com` URLs. If possible, can you tell me the exact URL Dot is making a request to?

**Comment by bm92aWJldnJvcw** [comment]
@trevorthalacker `network.captive-portal-service.enabled` is not disabled/False when I install Dot Browser (87/86) and go to the about:config... 

This test is with last 86 ver of Dot, same is for latest 87 ver btw.
 
at initial launch after installation:

![dot 86 requests](https://user-images.githubusercontent.com/68984972/113473920-33025a80-9432-11eb-9680-7b484a5fcc1a.PNG)

after toggling it to false and relaunching:

![dot 86 requests after toggling about config network captive to false](https://user-images.githubusercontent.com/68984972/113473931-40b7e000-9432-11eb-9834-27375ef2e4b1.PNG)

**Comment by SKBotNL** [comment]
![afbeelding](https://user-images.githubusercontent.com/68018116/113476803-1ab82d00-947e-11eb-8acb-3418528e2329.png)
Yep it's indeed enabled by default

**Comment by kierandrewett** [comment]
I absolutely agree, this should be disabled by default. I will get this fixed asap.
