### ISSUE TITLE
Dot uses Amazon as the default search engine

### ISSUE THREAD

**Issue by ItsJamie9494** [dothq/browser-desktop#262]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
Search, Addressbar

**Describe the bug**
By default, Dot Browser should use DuckDuckGo as the search engine. However, on a fresh build of Dot, the default search engine is set to Amazon.com
**To Reproduce**
1. Build Dot Browser
2. Open Dot Browser
3. Attempt Search

**Expected behavior**
Dot would use DuckDuckGo to search

**Screenshots**
![image](https://user-images.githubusercontent.com/22264706/113806428-1d817f00-9717-11eb-9da8-c619be58db70.png)
![image](https://user-images.githubusercontent.com/22264706/113806500-3c801100-9717-11eb-8988-fcd852d324b6.png)

**System Information (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04 (?)

**Dot Browser Information (please complete the following information):**
 - Version: 87.0
 - Site you were on before the bug appeared: New Tab Page

**Comment by kierandrewett** [comment]
You have probably built the browser incorrectly as the UI or the icons have not been changed. I was unable to reproduce this issue too, closing.
