### ISSUE TITLE
prefers-color-scheme: dark is never applied

### ISSUE THREAD

**Issue by trickypr** [dothq/browser-desktop#263]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
Fingerprinting

**Describe the bug**
The browser does not appear to emit `prefers-color-scheme: dark` when the os is set to dark theme or browser is set to dark theme.

**To Reproduce**
1. Visit a website that uses `prefers-color-scheme: dark` to set dark theme. E.g. https://new.dothq.co
2. Set your system to use a dark theme
3. Observe the page not being dark

**Expected behavior**
`prefers-color-scheme: dark` should be emitted when the system is in dark theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/23250792/114267713-cf0d0280-99ec-11eb-9d85-5d35df0bcc3b.png)

**System Information (please complete the following information):**
 - OS: Manjaro and MacOS
 - Version: Up to date (rolling release) and Big Sur respectively 

**Dot Browser Information (please complete the following information):**
 - Version: Latest nightly flatpak
 - Site you were on before the bug appeared: https://new.dothq.co

**Additional context**
This issue is not present on firefox stable.

**Comment by kierandrewett** [comment]
This is occurring with the automatic theme and you have set your system theme to dark right?

**Comment by trickypr** [comment]
Correct

**Comment by kierandrewett** [comment]
It works for me fine on Linux, however I am unsure about macOS. It should work on macOS. Try it on Firefox and see if it works there.

**Comment by trickypr** [comment]
So, it turns out that the [resist fingerprinting keyword does this](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS#view_media_rules_for_prefers-color-scheme). We could turn it off and implement our own, less invasive implementation, or we could keep it on and leave things broken.

**Comment by kierandrewett** [comment]
I think we should turn off resist fingerprinting for colour scheme

**Comment by trickypr** [comment]
If that is possible, yes

**Comment by kierandrewett** [comment]
Very much possible, does anyone want to open a PR for this?

**Comment by kierandrewett** [comment]
See dothq/browser-desktop#20 for more info. Closing.
