### ISSUE TITLE
Highlight/Shadow around box when I right-click

### ISSUE THREAD

**Issue by condense-fidelity-elope** [dothq/browser-desktop#264]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**

**Describe the bug**
When I right click, the box that shows up has a outline around, like this shadow

**To Reproduce**
Right click on any website

**Expected behavior**
The shadow should not appear

**Screenshots**
https://cdn.discordapp.com/attachments/572148854330360008/831217970805735474/IMG_20210412_132255.jpg

**System Information (please complete the following information):**
 - OS: Arch Linux
 - Version: Latest April 1st update

**Dot Browser Information (please complete the following information):**
 - Version: 87.0

**Additional context**

**Comment by trickypr** [comment]
This has likely related to your compositor, although there should be some way of us telling the compositor to not do this.


Update: I fixed this by adding the following to my picom config.
```
shadow-exclude = [
    #....
    "class_g = 'Dot' && argb",
    #....
]
```

We do need to work on getting this stuff into other compositor configs though
