### ISSUE TITLE
Pinned Tabs Becoming Hidden When Too Many Tabs Are Open

### ISSUE THREAD

**Issue by proudmuslim-dev** [dothq/browser-desktop#265]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**

The tab bar.

**Describe the bug**
Pinned tabs are becoming hidden once too many tabs have been opened.

**To Reproduce**
1. Pin a tab.
2. Open enough new tabs that the arrow icons for scrolling show up.
3. See the arrow on the left side.
4. Observe that the pinned tab is now hidden, however it can still be accessed through the use of the built-in `ctrl+ pageup/pagedown` keybinds.

**Expected behavior**
The arrow is supposed to appear next to the pinned tab, not over it.

**Screenshots**
Expected Behavior:

![image](https://user-images.githubusercontent.com/69869443/114810481-b8273100-9d9b-11eb-9d6f-81aac19a9c66.png)
![image](https://user-images.githubusercontent.com/69869443/114810494-beb5a880-9d9b-11eb-87d7-9dd09b59ddba.png)

What Occurs:

(Before opening enough tabs for this to happen)
![image](https://user-images.githubusercontent.com/69869443/114810595-ee64b080-9d9b-11eb-96cf-c248b858b646.png)
![image](https://user-images.githubusercontent.com/69869443/114810673-1b18c800-9d9c-11eb-9805-b985ecdc5e5d.png)

(After opening enough tabs for this to happen))
![image](https://user-images.githubusercontent.com/69869443/114810642-0e946f80-9d9c-11eb-8a13-20228f125075.png)
![image](https://user-images.githubusercontent.com/69869443/114810630-050b0780-9d9c-11eb-98e5-d7b57301cf3d.png)

**System Information (please complete the following information):**
 - OS: Arch Linux, on Wayland (Swaywm)

**Dot Browser Information (please complete the following information):**
 - Version: This version of [87.0 nightly](https://github.com/dothq/browser-desktop/releases/tag/87.0-738967408), released on April 11th.

**Comment by trickypr** [comment]
Can confirm that this issue is also present on macos

**Comment by kierandrewett** [comment]
what

**Comment by Leaor** [comment]
i dont fucking know i had the same thing

**Comment by Leaor** [comment]
Also when i try closing the dothq window it doesn't work

**Comment by trickypr** [comment]
dothq/browser-desktop@4fac458cc03e31ed1e0e9e838fe8d8f8f42c4cf8 should fix this
