### ISSUE TITLE
support for NT 5.1

### ISSUE THREAD

**Issue by andika207** [dothq/browser-desktop#269]
I can't install this browser on WinXP. 
it does nothing when I click on the exe file.
so it would be cool if you build a specific version for XP users.

**Comment by kierandrewett** [comment]
Apologies, currently we have no plans to support Windows XP. It would be a lot of work for just a handful of cases.

**Comment by andika207** [comment]
handful of cases ? LOL
Mozilla stupidly lost thousands of users when they dropped support for WinXP

**Comment by andika207** [comment]
I did read the introduction but I am unable to build it myself from the source code.
I would need a video tutorial for dummies

**Comment by kierandrewett** [comment]
> handful of cases ? LOL
> Mozilla stupidly lost thousands of users when they dropped support for WinXP
> 

It is just me working on the core desktop product ATM and I don't really want to start making core engine changes just so it can be run on Windows XP. Not a Windows user but I believe compatibility mode is a thing? Sorry if you've already tried that but perhaps that could let it run.

**Comment by kierandrewett** [comment]
> I did read the introduction but I am unable to build it myself from the source code.
> I would need a video tutorial for dummies 
> 

That is something we could consider making.
