### ISSUE TITLE
trying to install on windows 8.1 64 bit, returning error Requires windows 7 64 bit or higher

### ISSUE THREAD

**Issue by autoteelar** [dothq/browser-desktop#270]

**Comment by autoteelar** [comment]
also the button to download it through internet explorer didnt work lol, i like the funny page tho, and im sure the only use for internet explorer these days is downloading a better browser :D

**Comment by kierandrewett** [comment]
Have you got a screenshot of the error?

**Comment by autoteelar** [comment]
sure, ill have to get on my laptop (windows 8 pc) and get some screenshots. i got my main pc set up with linux properly now tho so ill probably just get it on there but i should still figure the root of this issue as well.

**Comment by autoteelar** [comment]
![image](https://user-images.githubusercontent.com/16366107/198886854-0414c14d-264e-42c3-a6b5-e6a925610acb.png)
so yeah when i open the exe it says extracting, then it says this once its done, ive tried compatibility mode for windows 7, runing as admin, idk much else what to do to debug this stuff on windows lol

**Comment by autoteelar** [comment]
i just installed and opened it up on linux no problem tho and wow, this browser is pretty nice and interesting, ive never seen anything like it, UI wise anyways. although its only been like 5 seconds so we'll see how it goes :)

**Comment by kierandrewett** [comment]
Hmm, that's really odd. Not sure why that error is showing up, I will try looking into this for you when I have time.

**Comment by autoteelar** [comment]
i figured it out,,,, for some reason this windows 8.1 is 32 bit. i will reinstall it as 64 bit unless theres a way to upgrade the OS without reinstalling

**Comment by autoteelar** [comment]
i mustve accidentially selected 32 bit somehow in the windows intaller setup,, i guess we can mark this as resolved :D
