### ISSUE TITLE
Provide a Flatpak as software package — for Linux systems

### ISSUE THREAD

**Issue by x80486** [dothq/browser-desktop#271]
[Flatpak](http://docs.flatpak.org/en/latest/introduction.html) is a technology for building, distributing, installing and running applications – primarily targeted at the Linux desktop and desktop applications.

Would be great (and convenient) to be able to install `Dot Browser` from `Flathub`.

**Comment by kierandrewett** [comment]
This is something we are planning as well as support for AppImage installation.
