### ISSUE TITLE
./mach import-patches fails

### ISSUE THREAD

**Issue by happy-code-time** [dothq/browser-desktop#272]
After all previous commands based on 

`https://developer.dothq.org/contributing/building_the_browser/linux.html`

trying to execute command  

`./mach import-patches`

inside dot directory

```
Executing mach from cwd /home/username/Documents/gecko-dev.
It looks like you are trying to run an unknown mach command: import-patches

Did you want to run any of these commands instead: import-pr, wpt-test-paths, wpt-update?

Run |mach help| to show a list of commands.
```
On branch 

`release`

**Comment by kierandrewett** [comment]
Interesting, I will take a look at this later today.

Thanks for reporting this!

**Comment by kierandrewett** [comment]
I have just pushed a fix for this. 

If you enter your `dot` directory and run the following commands:

```sh
git pull
./scripts/sync.py
```
You should then be able to run `./scripts/install_mach_commands.py`. If it's successful, you can just continue from [Importing patches](https://developer.dothq.org/contributing/building_the_browser/linux.html#importing-patches) in the documentation.

Let me know how it goes 👍
