### ISSUE TITLE
All new tab crash

### ISSUE THREAD

**Issue by judemont** [dothq/browser-desktop#273]
When I open a new tab or when I go to a website, I have a message telling me that the tab has crashed.

![Capture d’écran du 2023-03-10 21-21-04](https://user-images.githubusercontent.com/96385330/224421214-9a7f2146-ad7b-49c5-8cb9-e050bf159303.png)

My Operating system : ubuntu (linux)
Dot version : v87.0

**Comment by kierandrewett** [comment]
This is a known problem, we are currently in the process of reworking the whole browser (still built on Firefox). This is also why there hasn't been a new build since 2021.

**Comment by judemont** [comment]
Okay, thanks

**Comment by ioc2e3** [comment]
> 這是一個已知問題，我們目前正在重新設計整個瀏覽器（仍然基於 Firefox 建置）。這也是自 2021 年以來沒有新建築的原因。

but ...

It’s already 2024 ...

It's been a long time ...

.

**Comment by kierandrewett** [comment]
Yep, it will take a while unfortunately as trying to rebuild everything from scratch is quite difficult. Good progress is being made though and I'll announce something once it's in a useable state.

**Comment by ioc2e3** [comment]
> 是的，不幸的是，這需要時間，因為嘗試從頭開始重建一切是相當困難的。但是，我們正在取得良好的進展，一旦它達到可用狀態，我宣布一些事情。

that ...

Will there be Portable ?

Will there be a Traditional Chinese interface ?

.

**Comment by kierandrewett** [comment]
Yes there will be a portable version.

If you mean Traditional Chinese language option, yes, if we can find some people to maintain the Traditional Chinese language for Dot.
