### ISSUE TITLE
Change name of executable

### ISSUE THREAD

**Issue by arcolinuxz** [dothq/browser-desktop#71]
![image](https://user-images.githubusercontent.com/36679406/137847774-3568800a-e8fd-4bab-a942-4d20786fb233.png)
If we want to install your application it conflicts with an already existing package.

Can you rename it to dot-browser for example?

Arch Linux 

Version 
https://aur.archlinux.org/packages/dot-bin/

**Comment by trickypr** [comment]
Hi, thanks for filling an issue, this appears to be a duplicate of a known issue (#604).

**Comment by dot-mike** [comment]
This is resolved as of https://github.com/dothq/browser-desktop/commit/845da3fb342d331527d986c23bc5496b3b93e311
