### ISSUE TITLE
"Message from Firefox"

### ISSUE THREAD

**Issue by itslevir** [dothq/browser-desktop#78]
**Preflight Checklist**
* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**

When starting the browser, there is a popup that Mozilla places to promote other Firefox products, like Firefox sync, and Firefox Lockwise. This is showing up in Dot.
**Describe the bug**
Usually, when starting Firefox, there is a "Notification from Mozilla" recommendation to use another Mozilla product, like Mozilla VPN, Firefox Lockwise, etc., etc. Apparently this has not been removed from Dot yet, because I recently started up Dot (v87.0, 64 bit on a Windows 10 machine) and saw this:
![image](https://user-images.githubusercontent.com/72626657/116903888-e3aa7800-abf1-11eb-954a-eeb9693b3923.png)
I'm guessing this is on purpose, since Dot uses Mozilla's sync/login, but you may want to think about changing "Firefox" to "Dot"
**To Reproduce**
1. Open Dot, not logged in

**Expected behavior**
Either no popup box at all, or removal of the Mozilla/Firefox branding

**Screenshots**
![image](https://user-images.githubusercontent.com/72626657/116904288-5c113900-abf2-11eb-9e0e-14561ee970ef.png)
![image](https://user-images.githubusercontent.com/72626657/116904820-0ab57980-abf3-11eb-9856-c5a0784121ba.png)
**System Information:**
 - OS: Windows 10 Education Edition (My school PC)
 - Version: 10.0.18363 build 18363

**Dot Browser Information:**
 - Version: v87.0
 - Start page

**Comment by SandroLinux** [comment]
Yes I get this as well

**Comment by itslevir** [comment]
Stale issue
