### ISSUE TITLE
Address bar and icons clipped into top edge of window - Linux

### ISSUE THREAD

**Issue by rohan-bansal** [dothq/browser-desktop#88]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**

Address bar

**Describe the bug**
The address bar and inline icons are clipped into the top edge of the window, see screenshot below. I don't believe this is a GTK issue, I reset my theme to default and the bug persists.

**To Reproduce**

1. Launch the browser on Linux (Pop OS 20.04)

**Expected behavior**
The address bar appears normally, without being cut off by the window.

**Screenshots**

![image](https://user-images.githubusercontent.com/36248672/127092616-ff31458a-e950-4d49-8aaf-adfc2ea15e0e.png)

**System Information (please complete the following information):**
 - OS: Pop! OS
 - Version: 20.04
 - Kernel: 5.11.0-7620-generic

**Dot Browser Information (please complete the following information):**
 - Version: 87.0
 - Site you were on before the bug appeared: homepage

**Additional context**
Running in hybrid graphics mode with an RTX 2060 & Intel UHD Graphics 630. Theme in screenshot is Sweet-Mars, but disabled it is the Pop! OS default.

**Comment by kierandrewett** [comment]
Duplicate of dothq/browser-desktop#84
