### ISSUE TITLE
UI cut on Windows 7

### ISSUE THREAD

**Issue by Bellisario** [dothq/browser-desktop#89]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**

App windows

**Describe the bug**
On Windows 7, the app is not properly shown: the up part is cut and can be difficult to use it. If it is in all-screen mode, the problem doesn't resolves and the close, reduce and all-screen enable/disable buttons of Windows are cut, too.

**To Reproduce**
Just open the app on Windows 7.

**Expected behavior**
The app need to don't cut parts of the UI and a part of button described up.

**Screenshots**
![image](https://user-images.githubusercontent.com/72039923/126864274-989fdfef-9cc5-4b39-96ba-43330e3f0852.png)

**System Information (please complete the following information):**
 - OS: Windows
 - Version: 7

**Dot Browser Information (please complete the following information):**
 - Version: Nightly v87.0 - 2021-07-22 (87.0-2021-07-22)
 - Site you were on before the bug appeared: Not relevant, problem is in all opened pages and all sites.

**Additional context**
None.

**Comment by kierandrewett** [comment]
Issue already reported, dothq/browser-desktop#84. Closing.
