### ISSUE TITLE
Weird background on tabs

### ISSUE THREAD

**Issue by SKBotNL** [dothq/browser-desktop#90]
**Preflight Checklist**
* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
Browser

**Describe the bug**
A Weird background on tabs, it may be intended but it just cuts off weirdly

**To Reproduce**
1. Open a few tabs
2. See background

**Screenshots**
![dot_XAm7K4GvlD](https://user-images.githubusercontent.com/68018116/110849008-033ab980-82af-11eb-9cd7-9c4b621aa1a0.png)
![dot_2wENqzR1mF](https://user-images.githubusercontent.com/68018116/110849017-059d1380-82af-11eb-8345-cd9601426206.png)

**System Information (please complete the following information):**
 - OS: Windows 10
 - Version: 20H2

**Dot Browser Information (please complete the following information):**
 - Version: Nightly 86
 - Site you were on before the bug appeared: N/A

**Comment by kierandrewett** [comment]
We know about this already from your own issue dothq/browser-desktop#84, closing.
