### ISSUE TITLE
/usr/bin/dot owned by graphviz (gimp dependency)

### ISSUE THREAD

**Issue by jrvgr** [dothq/browser-desktop#91]
* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
AUR package

**Describe the bug**
Hi guys, I'm interested in this project but i noticed a pretty major flaw when it comes to the current way of storing the binary on Linux. As is dot will try to use `/usr/bin/dot` but that is already acquired by "graphviz" which is a dependency of the GIMP program. I would suggest changing it to `dot-browser` or something similar 

**To Reproduce**
1. Install GIMP on Arch/Manjaro
2. Attempt to install dot browser through AUR
4. See conflict

**Expected behavior**
Install without conflicts

**System Information (please complete the following information):**
 - OS: Arch / Manjaro
 - Version: Rolling

**Dot Browser Information (please complete the following information):**
 - Version: Current AUR 

**Additional context**
This should have been fixed with dothq/browser-desktop#104

**Comment by trickypr** [comment]
Are you installing this through AUR or some other platform?

**Comment by jrvgr** [comment]
the AUR dot-bin version

**Comment by trickypr** [comment]
This has been resolved (see dothq/browser-desktop#104), however @EnderDev still needs to deploy it to AUR.
