### ISSUE TITLE
[Bug]: Won't quit or force quit Mac.

### ISSUE THREAD

**Issue by mistysloth** [dothq/browser-desktop#95]
### Preflight Checklist

- [x] I have checked the [issue tracker](https://github.com/dothq/browser/issues) for issues that may be similar to mine.
- [X] I have checked whether this issue can be reproduced on another setup (e.g. other operating system or browser version/channel)
- [X] I have checked that the title is not empty.

### Description

The browser will quit no matter what I do. A possible explanation was that my power went off while I was doing A 10.3-gigabyte download.

### Steps to Reproduce

1. Download A big file. (5+ GB)
2. Let your power run out in the middle of doing so.
3. Startup again.

### Actual result

https://user-images.githubusercontent.com/93560458/156055431-5bf1cb83-18fb-4de9-a5a6-2e55a4fe22db.mov

### Expected result

The app should have opened with no problems.

### Browser version

87.0

### Browser build date

Impossible to know.

### Browser channel

Nightly

### Other information

Nope!

**Comment by kierandrewett** [comment]
Does the browser close through Cmd+Option+Escape?

**Comment by mistysloth** [comment]
No. I can't even find its Activity Monitor Process to quit.

**Comment by mistysloth** [comment]
Fixed. Had to shut down computer and that fixed it.
