### ISSUE TITLE
DOT BROWSER

### ISSUE THREAD

**Issue by honorio1951** [dothq/browser-desktop#97]
HELLO SOMEBODY HAS SEEN DOT BROWSER ????
I TRIED INSTALL IT IN UBUNTU CINNAMON 21, BUT  I COULD NOT AND NEITHER COULD NOT AN IMAGE OF TERMINAL.
I'M NOT VERY EXPERTISE, SO ANOTHER TUTO WILL BETTER.

THANKS IN ADVANCE

**Comment by kierandrewett** [comment]
It should work in Ubuntu 21. Are you running the .deb and what command did you run to install it?

**Comment by UnnknownMk** [comment]
dude is that a Sphynx cat there buitifull

**Comment by kierandrewett** [comment]
Yes, it is. They are indeed beautiful.

**Comment by ClutchKick2207** [comment]
Hey,
To install an AppImage, all you have to do is make it an executable. You are able to do this with a `chmod u+x` command, and then pointing it to where your appimage is located, for example `chmod u+x ~/user_name/Downloads/example-file.AppImage` . Hope that helps ;) and feel free to have a look on the Discord server for any more help.

**Comment by ClutchKick2207** [comment]
After you make it executable, you can then move the file somewhere such as applications to allow for you to launch it using any standard launcher. Your best option though would be to run the following command `~/user_name/example/directory/example-file.AppImage --register-app` to allow for your OS to recognise it as an app image. If you are not comfortable using a terminal, I would recommend you go on an OS such as ElementaryOS, which has GUI based installers such as Eddy (which I personally recommend). Elementary also has the feature of every normal task having a GUI based system to allow for you to do it (making it easier if you are not comfortable with a terminal). Hope that helps.
