### ISSUE TITLE
DRM is disabled by default

### ISSUE THREAD

**Issue by trickypr** [dothq/browser-desktop#98]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**
Preferences / DRM

**Describe the bug**
DRM is disabled, breacking sites like netflix

**To Reproduce**
1. Go to settings
2. Search for DRM
3. See the unchecked checkbox 

**Expected behavior**
Should be enabled by default

**Screenshots**

**System Information (please complete the following information):**
 - OS: Linux
 - Version: Manjaro

**Dot Browser Information (please complete the following information):**
 - Version: nightly
 - Site you were on before the bug appeared: neflix

**Comment by dancojocaru2000** [comment]
One of Dot's ideas is that it's a privacy respecting browser. DRM is, in some or all cases, directly against that.

It's just an option in settings. Toggle it and you're done. Why should it be the default?

**Comment by kierandrewett** [comment]
I agree, DRM is designed to be disabled by default in Dot. If DRM is needed to access some content, we can prompt you to pick whether you want to enable it or not. But by default, it will be disabled. Closing.
